
# some variables are maintained by terraform. Will need to look at TF output to verify these variables
pod_net: 172.17.0.0/16
IPADDR: 10.0.0.11

packages:
  - kubelet
  - kubectl
  - kubeadm

setup_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

pre_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common