name: Build Infrastructure
on: ["push"]
jobs:
  build:
    name: Check and deploy terraform
    runs-on: ubuntu-latest
    container: mjkli/iac-terraform:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-west-1"
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
      
      - name: Terraform validate
        run: terraform validate
        working-directory: Infra/dev
      
      - name: Terraform Init
        run: terraform init
        working-directory: Infra/dev
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        working-directory: Infra/dev
      
      - name: Terraform Plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terrafrom Apply
        run: terrafrom apply -auto-approve -input=false
        working-directory: Infra/dev


      


