name: Build Infrastructure
on: ["push"]
jobs:
  build:
    name: Check terraform
    runs-on: ubuntu-latest
    container: mjkli/iac-terraform:latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - run: |
          export AWS_ACCESS_KEY_ID = ${{secrets.AWS_ACCESS_KEY_ID}}
          export AWS_SECRET_ACCESS_KEY = ${{secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_DEFAULT_REGION="us-west-1"
          cd Infra/dev
      
      - name: Terraform format
        run: terraform fmt -check
      
      - name: Terraform validate
        run: terraform validate
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
      
      - name: Terraform Plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terrafrom Apply
        run: terrafrom apply -auto-approve -input=false


      


