name: Build Dev Infrastructure
on:
  push:
    paths:
      - infra/*
      - infra/modules/**
      - infra/dev/**
      - .github/workflows/build-infra.yml
#on: ["push"]
defaults:
  run:
    working-directory: infra/dev
jobs:
  build:
    name: Check and deploy terraform
    runs-on: ubuntu-latest
    container: mjkli/iac-terraform:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-west-1"
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
      
      - name: Terraform Init
        run: terraform init

      
      - name: Terraform validate
        run: terraform validate

      
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var "db_username=${{ secrets.DB_USERNAME }}" -var "db_password=${{ secrets.DB_PASSWORD }}" -var "api_token=${{ secrets.API_KEY }}"

      - name: Terraform Plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terrafrom Apply
        run: terraform apply -auto-approve -input=false -var "db_username=${{ secrets.DB_USERNAME }}" -var "db_password=${{ secrets.DB_PASSWORD }}" -var "api_token=${{ secrets.API_KEY }}"
      
      - name: Wait 2 min for runners to apply
        run: sleep 120



      


