name: Configure Infrastructure
#on:
#  push:
#    paths:
#      - Config/**
on: ["push"]
defaults:
  run:
    working-directory: config
jobs:
  check:
    name: check nodes
    runs-on: [self-hosted, ansible]
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
      
      - name: Ping
        run: ansible -i hosts all -m ping

  configure_masterNode:
    name: configure_masterNode
    needs: check
    runs-on: [self-hosted, ansible]
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: install kubernetes packages
        run: ansible-playbook -i hosts cluster_config.yml
  
  configure_workerNodes:
    name: configure_workernodes
    needs: configure_masterNode
    runs-on: [self-hosted, ansible]
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
      
      - name: install workernodes
        run: ansible-playbook -i hosts woker_node.yml


