name: Deploy Applications
on:
  push:
    paths:
      - application/**
      - .github/workflows/deploy_app.yml
#on: ["push"]
defaults:
  run:
    working-directory: application
jobs:
  deploy_ipam:
    name: deploy Ipam pods
    runs-on: [self-hosted, master-node]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: deploy ipam
        run: kubectl apply -f ipam/ipam-deployment.yaml

      - name: deploy ipam service
        run: kubectl apply -f ipam/ipam-service.yaml